### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by Ser3196** [gvlfm78/BukkitHotels#15]
```


[Hotels] Task #104 for Hotels v0.5.3 generated an exception
java.lang.NullPointerException
at gvlfm78.plugin.Hotels.managers.GameLoop.run(GameLoop.java:73) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by gvlfm78** [comment]
What is the name of the world(s) your hotels are in?

**Comment by Ser3196** [comment]
Mundo

**Comment by gvlfm78** [comment]
If you open one of the sign files in the Hotels/Signs folder, what does it say after world: ?

**Comment by Ser3196** [comment]
No text

**Comment by gvlfm78** [comment]
Well then that would be the problem. I do not know why that happened, and I will investigate, but fro now you can just add Mundo into that space and see if it works

**Comment by Ser3196** [comment]
I think it was a server problem, because the file is empty
With authme just happened, all data is erased

**Comment by Ser3196** [comment]
Good job, plugin :+1: 
I will try reinstall the plugin

**Comment by gvlfm78** [comment]
So does it work now?

**Comment by Ser3196** [comment]
yes, I deleted signs files and work
you can add users to make their own hotel or you can make an administrator the money arrives from rents to a specific user?

**Comment by gvlfm78** [comment]
That is in plan for a future update, as you can see from the [To Do List](https://github.com/gvlfm78/BukkitHotels/wiki/To-Do-List). It is probably going to be Hotels 0.7
