### ISSUE TITLE
NPE on /ht create

### ISSUE THREAD

**Issue by Dizfunkshunal** [gvlfm78/BukkitHotels#23]
when i start my server I get this error in the log.

`[14:09:07] [Server thread/INFO]: [Hotels] Enabling Hotels v0.6.3
[14:09:07] [Server thread/WARN]: [Fatal Error] :1:1: Premature end of file.

[14:09:07] [Server thread/WARN]: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[14:09:07] [Server thread/WARN]:    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
[14:09:07] [Server thread/WARN]:    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
[14:09:07] [Server thread/WARN]:    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
[14:09:07] [Server thread/WARN]:    at gvlfm78.plugin.Hotels.HotelsUpdateChecker.updateNeeded(HotelsUpdateChecker.java:46)
[14:09:07] [Server thread/WARN]:    at gvlfm78.plugin.Hotels.HotelsMain.onEnable(HotelsMain.java:40)
[14:09:07] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[14:09:07] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:09:07] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:09:07] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[14:09:07] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539)
[14:09:07] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[14:09:07] [Server thread/WARN]: [Fatal Error] :1:1: Premature end of file.

[14:09:07] [Server thread/WARN]: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[14:09:07] [Server thread/WARN]:    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
[14:09:07] [Server thread/WARN]:    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
[14:09:07] [Server thread/WARN]:    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
[14:09:07] [Server thread/WARN]:    at gvlfm78.plugin.Hotels.HotelsUpdateChecker.updateNeeded(HotelsUpdateChecker.java:46)
[14:09:07] [Server thread/WARN]:    at gvlfm78.plugin.Hotels.HotelsMain.onEnable(HotelsMain.java:42)
[14:09:07] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[14:09:07] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:09:07] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:09:07] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[14:09:07] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270)
[14:09:07] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539)
[14:09:07] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[14:09:07] [Server thread/INFO]: [Hotels] Hotels v0.6.3 has been enabled correctly`

what research i have done, i am unable to fix this on my end.

Also when i try to make a new hotel it gives an internal error msg.

`[14:11:53] [Server thread/INFO]: Dizfunkshunal issued server command: /ht create Hobo1
[14:11:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ht' in plugin Hotels v0.6.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_71]
    at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1084) ~[?:1.8.0_71]
    at java.util.concurrent.ConcurrentHashMap.<init>(ConcurrentHashMap.java:852) ~[?:1.8.0_71]
    at com.sk89q.worldguard.protection.regions.ProtectedRegion.setFlags(ProtectedRegion.java:462) ~[?:?]
    at gvlfm78.plugin.Hotels.managers.WorldGuardManager.setFlags(WorldGuardManager.java:298) ~[?:?]
    at gvlfm78.plugin.Hotels.managers.WorldGuardManager.hotelFlags(WorldGuardManager.java:307) ~[?:?]
    at gvlfm78.plugin.Hotels.HotelsCreationMode.createHotelRegion(HotelsCreationMode.java:122) ~[?:?]
    at gvlfm78.plugin.Hotels.HotelsCreationMode.hotelSetup(HotelsCreationMode.java:92) ~[?:?]
    at gvlfm78.plugin.Hotels.handlers.HotelsCommandExecutor.cmdCreate(HotelsCommandExecutor.java:55) ~[?:?]
    at gvlfm78.plugin.Hotels.handlers.HotelsCommandHandler.onCommand(HotelsCommandHandler.java:72) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f]
    ... 15 more`

I think they may be part of the same problem.  The hotel does show up in the hotel list even with the error.

**Comment by gvlfm78** [comment]
The first error I am aware of and has alreayd been reported on the Spigot discussion page. It has to do with the update checker and nothing to do with the next error.

For the second error, could you try with /ht c instead of /ht create, and could you try without the number, and could you also try all lowercase? These are just suggestions to try and figure out where the problem is.

**Comment by Dizfunkshunal** [comment]
tried with /ht c hobo1  -  all lower case and tried just hobo  with out the number.  Still gives an error

**Comment by gvlfm78** [comment]
Could you check if your flags.yml file was generated correctly? Could you try having it re-generate?

**Comment by Dizfunkshunal** [comment]
Yea it appears to have generator correctly, I also regenerated. Also tried installing on another server.

**Comment by gvlfm78** [comment]
In what way are you selecting the region for the hotel? Do you have it set to cuboid and are selecting the two corners?

**Comment by Dizfunkshunal** [comment]
Using worldedit wand I select the 2 corners  then expand the selection 10 block up  and then try to create the hotel

so
left click select
right click select opposite corner
//expand 10 up
/ht create Hobo

**Comment by gvlfm78** [comment]
Could you try in a different location in the world? Or even in a different world? I'm trying out where the issue is first so that I can fix it.

What version of Hotels, Bukkit/Spigot, WorldEdit & WorldGuard, Vault do you have?

**Comment by gvlfm78** [comment]
@Dizfunkshunal Could you try with the latest [test version of Hotels 1.0.0](https://jenkins-gvl.rhcloud.com/job/Hotels/12/artifact/target/hotels.jar)?

**Comment by Ser3196** [comment]
I have tried with hotels 1.0.0 and says 
![captura de pantalla 2016-12-15 a las 15 52 32](https://cloud.githubusercontent.com/assets/10505413/21237636/91b26a72-c2de-11e6-89e4-54ad37afd718.png)

**Comment by Ser3196** [comment]
@gvlfm78 it's because the world edit and world guard version, I tested it

**Comment by Ser3196** [comment]
but still no permission in 1.0.0

**Comment by gvlfm78** [comment]
@Ser3196 I don't know what you mean, but the Hotels test version you used is quite old. Could you try with the attached version (extract the jar)? Please backup your server first as it is not a fully tested version and possibly contains many bugs.
[Hotels_test.zip](https://github.com/gvlfm78/BukkitHotels/files/655670/Hotels_test.zip)

**Comment by Ser3196** [comment]
If you have the last version of WorldEdit and WorldGuard, you can't create a hotel and appears the bug that @Dizfunkshunal wrote (`[14:11:53] [Server thread/INFO]: Dizfunkshunal issued server command: /ht create Hobo1 [14:11:53] [Server thread/ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'ht' in plugin Hotels v0.6.3 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71] at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71] Caused by: java.lang.NullPointerException at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_71] at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1084) ~[?:1.8.0_71] at java.util.concurrent.ConcurrentHashMap.<init>(ConcurrentHashMap.java:852) ~[?:1.8.0_71] at com.sk89q.worldguard.protection.regions.ProtectedRegion.setFlags(ProtectedRegion.java:462) ~[?:?] at gvlfm78.plugin.Hotels.managers.WorldGuardManager.setFlags(WorldGuardManager.java:298) ~[?:?] at gvlfm78.plugin.Hotels.managers.WorldGuardManager.hotelFlags(WorldGuardManager.java:307) ~[?:?] at gvlfm78.plugin.Hotels.HotelsCreationMode.createHotelRegion(HotelsCreationMode.java:122) ~[?:?] at gvlfm78.plugin.Hotels.HotelsCreationMode.hotelSetup(HotelsCreationMode.java:92) ~[?:?] at gvlfm78.plugin.Hotels.handlers.HotelsCommandExecutor.cmdCreate(HotelsCommandExecutor.java:55) ~[?:?] at gvlfm78.plugin.Hotels.handlers.HotelsCommandHandler.onCommand(HotelsCommandHandler.java:72) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.0-20160621a.jar:git-Spigot-c55900f-9af379f] ... 15 more`) 
it's because he have the last version of WE and WorldGuard (that happened to me).
Works with older WorldEdit (6.1) and WorldGuard (6.1) versions

**Comment by Ser3196** [comment]
I can't unzip the file :(

**Comment by gvlfm78** [comment]
How come?

**Comment by Ser3196** [comment]
![captura de pantalla 2016-12-15 a las 17 36 43](https://cloud.githubusercontent.com/assets/10505413/21241156/1e9672fe-c2ed-11e6-9712-7eb44b8bccf1.png)
and on the host
![captura de pantalla 2016-12-15 a las 17 38 01](https://cloud.githubusercontent.com/assets/10505413/21241194/49735e60-c2ed-11e6-80ea-c49fed5cf67d.png)

**Comment by gvlfm78** [comment]
OK I'll have to resend it but i can't right now

**Comment by gvlfm78** [comment]
Here I managed to get the Jenkins back up, you can try [this build](https://jenkins-gvl.rhcloud.com/job/Hotels/47/) but make sure to back up the server files first as I haven't fully tested everything.

**Comment by Ser3196** [comment]
It's not a WorldEdit problem, it's with WorldGuard
When I tried with WorldGuard 6.2 this happened:
![captura de pantalla 2016-12-17 a las 21 34 49](https://cloud.githubusercontent.com/assets/10505413/21290631/1dd50ece-c4a1-11e6-9dc3-97a06930134b.png)
but then I downgraded to WorldGuard 6.1 and worked

**Comment by gvlfm78** [comment]
@Ser3196 What version of Hotels did you test that on?

**Comment by Ser3196** [comment]
1.0.0
But also happens in 0.6.4

**Comment by Dani9OO** [comment]
Can confirm, WorldGuard 6.2 always throws 

> An internal error ocurred while attempting to perform this command

 (In both Hotels latest build and in Hotels 0.6.4) when you try to create a room or an hotel, downgrading to **[worldguard 6.1.2](https://dev.bukkit.org/projects/worldguard/files/920773)** will **fix** this error

**Comment by gvlfm78** [comment]
Could you try with the [latest test build](https://jenkins-gvl.rhcloud.com/job/Hotels/lastSuccessfulBuild/) of Hotels? There might still be a few bugs, but it is mostly functional. If you find any other bugs please report

**Comment by gvlfm78** [comment]
Same issue as #28
