### ISSUE TITLE
Command Errors and Room Signs not update

### ISSUE THREAD

**Issue by StandbyGamer** [gvlfm78/BukkitHotels#29]
Aloha,
when i use the commands:

/ht create "hotelname"
/ht room "hotelname" "roomnr"

• 1) I see in the Chat a Error: An internal error occurred while attempting to perform this command
The two commands works with the Error. I use Spigot 1.11.2.

• 2) The next Problem the Room Signs will not update when a Player rent a room.
Example: The room is rented and the Room Sign show the Room is vacant.

Error Log from **(1)**:

```
[20:14:39 INFO]: StandbyGamer issued server command: /ht create MyHotel
[20:14:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ht' in plugin Hotels v0.6.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at gvlfm78.plugin.Hotels.managers.WorldGuardManager.setFlags(WorldGuardManager.java:284) ~[?:?]
        at gvlfm78.plugin.Hotels.managers.WorldGuardManager.hotelFlags(WorldGuardManager.java:302) ~[?:?]
        at gvlfm78.plugin.Hotels.HotelsCreationMode.createHotelRegion(HotelsCreationMode.java:122) ~[?:?]
        at gvlfm78.plugin.Hotels.HotelsCreationMode.hotelSetup(HotelsCreationMode.java:92) ~[?:?]
        at gvlfm78.plugin.Hotels.handlers.HotelsCommandExecutor.cmdCreate(HotelsCommandExecutor.java:55) ~[?:?]
        at gvlfm78.plugin.Hotels.handlers.HotelsCommandHandler.onCommand(HotelsCommandHandler.java:72) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        ... 15 more
		
		
[20:15:24 INFO]: StandbyGamer issued server command: /ht room MyHotel 2
[20:15:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ht' in plugin Hotels v0.6.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at gvlfm78.plugin.Hotels.managers.WorldGuardManager.setFlags(WorldGuardManager.java:196) ~[?:?]
        at gvlfm78.plugin.Hotels.managers.WorldGuardManager.roomFlags(WorldGuardManager.java:307) ~[?:?]
        at gvlfm78.plugin.Hotels.HotelsCreationMode.createRoomRegion(HotelsCreationMode.java:149) ~[?:?]
        at gvlfm78.plugin.Hotels.HotelsCreationMode.roomSetup(HotelsCreationMode.java:183) ~[?:?]
        at gvlfm78.plugin.Hotels.handlers.HotelsCommandHandler.onCommand(HotelsCommandHandler.java:472) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        ... 15 more
		
		
[20:17:41 ERROR]: Could not pass event PlayerInteractEvent to Hotels v0.6.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at gvlfm78.plugin.Hotels.managers.WorldGuardManager.setFlags(WorldGuardManager.java:196) ~[?:?]
        at gvlfm78.plugin.Hotels.managers.WorldGuardManager.roomFlags(WorldGuardManager.java:307) ~[?:?]
        at gvlfm78.plugin.Hotels.managers.SignManager.rentRoom(SignManager.java:318) ~[?:?]
        at gvlfm78.plugin.Hotels.managers.SignManager.useRoomSign(SignManager.java:257) ~[?:?]
        at gvlfm78.plugin.Hotels.HotelsListener.onSignUse(HotelsListener.java:87) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        ... 17 more
```

**Comment by gvlfm78** [comment]
Can you try with the [latest test build](https://jenkins-gvl.rhcloud.com/job/Hotels/96/) and see if the problem is still present? Keep in mind the test builds can be unstable so there may be other bugs

**Comment by StandbyGamer** [comment]
I test the last build and see the Error again. (on Screenshot the command used and the Plugin Version)

To german translation i read the Text on GitHub and will help you. All people disappeared, but not i. I worked yesterday 50% and now the rest 50%. I send you in SpigotMC a PM with the link to german translation. Give me 1 Day more is not necessary.


Screenshot:
![b6a23427a10c4f2087936fd5bfeb0df3](https://cloud.githubusercontent.com/assets/17263395/24682034/03056016-1998-11e7-9ed0-49f48f5ea4b5.png)

**Comment by StandbyGamer** [comment]
Okay Sorry my Error.. Now works fine with Plugin Version 1.0.0 :'D

**Comment by gvlfm78** [comment]
OK good that it works now. If you find any bugs with the 1.0.0 version please tell me. 

And thank you for offering to do the German translations, as the other people disappeared I trust you to not do the same.
