### ISSUE TITLE
Console spam and "An internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by Ser3196** [gvlfm78/BukkitHotels#31]
Console spam:

`[Server thread/WARN]: [Hotels] Task #115 for Hotels v1.0.1 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagRegistry
	at gvlfm78.plugin.Hotels.Room.exists(Room.java:104) ~[?:?]
	at gvlfm78.plugin.Hotels.Room.checkRent(Room.java:678) ~[?:?]
	at gvlfm78.plugin.Hotels.tasks.RoomTask.run(RoomTask.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagRegistry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 10 more`

This is when I use the command /ht create
`[Server thread/INFO]: Ser3195 issued server command: /ht create mihotel
[18:38:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ht' in plugin Hotels v1.0.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagRegistry
	at gvlfm78.plugin.Hotels.Hotel.exists(Hotel.java:71) ~[?:?]
	at gvlfm78.plugin.Hotels.HTCreationMode.hotelSetup(HTCreationMode.java:55) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdSurrogate.cmdCreate(HTCmdSurrogate.java:44) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.onCommand(HTCmdExecutor.java:70) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagRegistry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at gvlfm78.plugin.Hotels.Hotel.exists(Hotel.java:71) ~[?:?]
	at gvlfm78.plugin.Hotels.HTCreationMode.hotelSetup(HTCreationMode.java:55) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdSurrogate.cmdCreate(HTCmdSurrogate.java:44) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.onCommand(HTCmdExecutor.java:70) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	... 15 more`

**Comment by gvlfm78** [comment]
Have you updated WorldGuard?

**Comment by Pspman345** [comment]
Can confirm that I have the exact same problem too.
I'm using WorldGuard 6.2 as well.

**Comment by Ser3196** [comment]
I have updated WorldGuard and now all is running well
I am using spigot 1.9.4

**Comment by gvlfm78** [comment]
This really should just be the other side of issue #28 , where previously you got an error as Hotels hadn't updated but WorldGuard was, and now it is the other way around.
