### ISSUE TITLE
internal error when running the /ht create command

### ISSUE THREAD

**Issue by orion968** [gvlfm78/BukkitHotels#39]
[04:13:01] [Server thread/INFO]: orion968 issued server command: /ht c The Empty Arms
[04:13:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ht' in plugin Hotels v1.1.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagRegistry
	at gvlfm78.plugin.Hotels.Hotel.exists(Hotel.java:64) ~[?:?]
	at gvlfm78.plugin.Hotels.HTCreationMode.hotelSetup(HTCreationMode.java:50) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdSurrogate.cmdCreate(HTCmdSurrogate.java:37) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.lambda$new$1(HTCmdExecutor.java:22) ~[?:?]
	at gvlfm78.plugin.Hotels.utilities.HTSubCommand.run(HTSubCommand.java:106) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.onCommand(HTCmdExecutor.java:112) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagRegistry
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at gvlfm78.plugin.Hotels.Hotel.exists(Hotel.java:64) ~[?:?]
	at gvlfm78.plugin.Hotels.HTCreationMode.hotelSetup(HTCreationMode.java:50) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdSurrogate.cmdCreate(HTCmdSurrogate.java:37) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.lambda$new$1(HTCmdExecutor.java:22) ~[?:?]
	at gvlfm78.plugin.Hotels.utilities.HTSubCommand.run(HTSubCommand.java:106) ~[?:?]
	at gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.onCommand(HTCmdExecutor.java:112) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	... 15 more

**Comment by gvlfm78** [comment]
You should update WorldGuard.

Also a hotel can only have one word as a name, for example _TheEmptyArms_ or _The_Empty_Arms_
